# Generated by Django 4.2.4 on 2023-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2002-04-03'),
            preserve_default=False,
        ),
    ]
